version: "3.8"
services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: maslo
      MYSQL_DATABASE: draszanicusdb
      MYSQL_USER: giga_user
      MYSQL_PASSWORD: maslo
    ports:
      - "3306:3306"
    volumes:
      - ./draszanicusdb.sql:/docker-entrypoint-initdb.d/draszanicusdb.sql

  
